### ISSUE TITLE
编译时遇到了一个问题

### ISSUE THREAD

**Issue by FrankiezZZ** [CYBoys/Blogs#1]
您好，我是xcode10，按照博客的顺序操作，
编译遇到unable to find plugin '-MMD'这个问题，请问该如何解决呢。
![image](https://user-images.githubusercontent.com/12370297/55314387-9d2b4200-549c-11e9-86da-db5fa74a1cd8.png)

**Comment by LLLaiYoung** [comment]
-MMD 是什么？ namespace 的 name？建议不要用特殊字符命名

**Comment by FrankiezZZ** [comment]
我没有改名字，不太清楚这个-MMD是什么plugin。。我再找一找哈

**Comment by FrankiezZZ** [comment]
我在OTHER_CFLAGS那边少写了一个-Xclang，非常感谢~
