### ISSUE TITLE
添加自定义CC 后，不生成.o目标文件，link报错

### ISSUE THREAD

**Issue by jaimeCool** [CYBoys/Blogs#2]
ld: file not found: /Users/yaso/Library/Developer/Xcode/DerivedData/TestClang-dwqipspbmfqrmcdofwynnkpyybro/Build/Intermediates.noindex/TestClang.build/Debug-iphonesimulator/TestClang.build/Objects-normal/x86_64/ViewController.o

大佬，遇到过这个问题没

**Comment by LLLaiYoung** [comment]
把 DerivedData/TestClang-dwqipspbmfqrmcdofwynnkpyybro 路径的内容清空试试看呢，是不是编译的 clang 位置不对？或者 clang 没有编译成功。

**Comment by jaimeCool** [comment]
> 把 DerivedData/TestClang-dwqipspbmfqrmcdofwynnkpyybro 路径的内容清空试试看呢，是不是编译的 clang 位置不对？或者 clang 没有编译成功。

清空还是报错，clang插件已经生效，但就是没生成目标文件

**Comment by LLLaiYoung** [comment]
> > 把 DerivedData/TestClang-dwqipspbmfqrmcdofwynnkpyybro 路径的内容清空试试看呢，是不是编译的 clang 位置不对？或者 clang 没有编译成功。
> 
> 清空还是报错，clang插件已经生效，但就是没生成目标文件

有尝试过新建一个项目试试嘛？

**Comment by jaimeCool** [comment]
> 有尝试过新建一个项目试试嘛？
新建了 发现还是不行

**Comment by jaimeCool** [comment]
链接时 编译器还是使用xcode 字带的clang 吧

**Comment by LLLaiYoung** [comment]
> 链接时 编译器还是使用xcode 字带的clang 吧

按照这篇文章弄一下试试呢，https://github.com/CYBoys/Blogs/blob/master/LLVM_Clang/LLVM%20%26%20Clang%20%E5%85%A5%E9%97%A8.md

**Comment by jaimeCool** [comment]
> > 链接时 编译器还是使用xcode 字带的clang 吧
> 
> 按照这篇文章弄一下试试呢，https://github.com/CYBoys/Blogs/blob/master/LLVM_Clang/LLVM%20%26%20Clang%20%E5%85%A5%E9%97%A8.md

就是按这个弄的，除了我们的插件不一样，Xcode  10.2.1你那边OK吗

**Comment by LLLaiYoung** [comment]
> > > 链接时编译器还是使用xcode字带的clang吧
> > 
> > 
> > 按照这篇文章弄一下试试呢，[https：//github.com/CYBoys/Blogs/blob/master/LLVM_Clang/LLVM%20%26%20Clang%20%E5%85%A5%E9%97%A8。 MD](https://github.com/CYBoys/Blogs/blob/master/LLVM_Clang/LLVM%20%26%20Clang%20%E5%85%A5%E9%97%A8.md)
> 
> 就是按这个弄的，除了我们的插件不一样，Xcode 10.2.1你那边好吗

10.2.1 没测试，现在电脑没环境了。使用 Xcode 自带的 clang 没有问题吧？

**Comment by jaimeCool** [comment]
> > > > 链接时编译器还是使用xcode字带的clang吧
> > > 
> > > 
> > > 按照这篇文章弄一下试试呢，[https：//github.com/CYBoys/Blogs/blob/master/LLVM_Clang/LLVM%20%26%20Clang%20%E5%85%A5%E9%97%A8。 MD](https://github.com/CYBoys/Blogs/blob/master/LLVM_Clang/LLVM%20%26%20Clang%20%E5%85%A5%E9%97%A8.md)
> > 
> > 
> > 就是按这个弄的，除了我们的插件不一样，Xcode 10.2.1你那边好吗
> 
> 10.2.1 没测试，现在电脑没环境了。使用 Xcode 自带的 clang 没有问题吧？

**Comment by jaimeCool** [comment]
> > > > > 链接时编译器还是使用xcode字带的clang吧
> > > > 
> > > > 
> > > > 按照这篇文章弄一下试试呢，[https：//github.com/CYBoys/Blogs/blob/master/LLVM_Clang/LLVM%20%26%20Clang%20%E5%85%A5%E9%97%A8。 MD](https://github.com/CYBoys/Blogs/blob/master/LLVM_Clang/LLVM%20%26%20Clang%20%E5%85%A5%E9%97%A8.md)
> > > 
> > > 
> > > 就是按这个弄的，除了我们的插件不一样，Xcode 10.2.1你那边好吗
> > 
> > 
> > 10.2.1 没测试，现在电脑没环境了。使用 Xcode 自带的 clang 没有问题吧？

自带clang 没问题

**Comment by YangXiaoYu123123** [comment]
需要在配置 Other C Flag和CC的User-Defined之前先正常编译一遍，再添加配置才能编译，Xcode 10.3试了可以编译

**Comment by jaimeCool** [comment]
> 需要在配置 Other C Flag和CC的User-Defined之前先正常编译一遍，再添加配置才能编译，Xcode 10.3试了可以编译

这是因为你添加之前已经使用自定clang 生成了.o 文件，后面自定义clang 都没有重新生成

**Comment by YangXiaoYu123123** [comment]
不是，是用的我自己编译的clang编译的，而且clean之后依然可以编译
![企业微信截图_0a6971c7-d18f-458c-85ca-ef24e8c67b40](https://user-images.githubusercontent.com/6002068/63497934-76c37d00-c4f7-11e9-91bf-6c8ee4785a0f.png)

**Comment by jaimeCool** [comment]
各位有没有 -ast-dump 过.h 文件？  -isysroot 引入了iPhoneSimulator12.2.sdk   发现各种 unknown type name 'NSString'

**Comment by jaimeCool** [comment]
> 不是，是用的我自己编译的clang编译的，而且clean之后依然可以编译
> ![企业微信截图_0a6971c7-d18f-458c-85ca-ef24e8c67b40](https://user-images.githubusercontent.com/6002068/63497934-76c37d00-c4f7-11e9-91bf-6c8ee4785a0f.png)

link 不报错吗？ 我clean之后就报错  .o找不到了

**Comment by YangXiaoYu123123** [comment]
你可以试试 clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -fmodules -fsyntax-only -Xclang -ast-dump [代码文件目录] 手动用命令编译试一下，如果报错的话可能是你的clang编译的有问题

**Comment by jaimeCool** [comment]
> 你可以试试 clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -fmodules -fsyntax-only -Xclang -ast-dump [代码文件目录] 手动用命令编译试一下，如果报错的话可能是你的clang编译的有问题

ast-dump  .m 文件是完全没问题的，现在的问题是ast-dump .h文件时，在查找到Foundtion 里面的时候报错
![image](https://user-images.githubusercontent.com/10650365/63563313-3ca7b900-c593-11e9-93cd-cd3a02609cfa.png)

**Comment by YangXiaoYu123123** [comment]
.m可以就行 编译的就是.m文件，你dump .h文件干嘛？
