### ISSUE TITLE
按照配置后还是编译报错Symbol not found: __ZN5clang12ast_matchers16objcPropertyDeclE Expected in: flat namespace

### ISSUE THREAD

**Issue by XcqRomance** [CYBoys/Blogs#3]
Xcode: 10.2.1
错误信息：
error: unable to load plugin '/Users/xcq/Desktop/llvm/llvm_xcode/Debug/lib/QTPlugin.dylib': 'dlopen(/Users/xcq/Desktop/llvm/llvm_xcode/Debug/lib/QTPlugin.dylib, 9): Symbol not found: __ZN5clang12ast_matchers16objcPropertyDeclE
  Referenced from: /Users/xcq/Desktop/llvm/llvm_xcode/Debug/lib/QTPlugin.dylib
  Expected in: flat namespace
 in /Users/xcq/Desktop/llvm/llvm_xcode/Debug/lib/QTPlugin.dylib'
Command /Users/xcq/Documents/llvm/build/Debug/bin/clang failed with exit code 1
配置信息：
![image](https://user-images.githubusercontent.com/12582128/63358970-81b6ca00-c39e-11e9-857e-265ff2a2e22b.png)
![image](https://user-images.githubusercontent.com/12582128/63359045-a4e17980-c39e-11e9-9b15-f0953d5992ee.png)
![image](https://user-images.githubusercontent.com/12582128/63359074-b034a500-c39e-11e9-827d-c8b9861677bf.png)

**Comment by haidragon** [comment]
我用的xcode11 也跟着网上那种XcodeHacking 发现不行，因为里面已经有了一个Clang LLVM- 1.0.xcplugin，然后我又去修改这个插件把clang的路径修改了，就会出现下面这个错误，后面用作者的方式什么也不修改就加一些编译选项就ok了。

```

error: unable to find plugin 'MyPlugin'
error: unable to load plugin '/Users/haidragon/Desktop/llvm_build/Debug/lib/MyPlugin.dylib': 'dlopen(/Users/haidragon/Desktop/llvm_build/Debug/lib/MyPlugin.dylib, 9): Symbol not found: __ZN5clang15PluginASTAction6anchorEv
  Referenced from: /Users/haidragon/Desktop/llvm_build/Debug/lib/MyPlugin.dylib
  Expected in: flat namespace
 in /Users/haidragon/Desktop/llvm_build/Debug/lib/MyPlugin.dylib'
```
