### ISSUE TITLE
请教一下 终端运行指令 没有任何东西输出是什么原因呢

### ISSUE THREAD

**Issue by mynameissujie** [CYBoys/Blogs#5]

**Comment by LLLaiYoung** [comment]
什么指令？

**Comment by mynameissujie** [comment]
/Users/laiyoung_/Documents/LLVM/llvm_xcode/Debug/bin/clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/ -Xclang -load -Xclang /Users/laiyoung_/Documents/LLVM/llvm_xcode/Debug/lib/QTPropertyCheckPlugin.dylib -Xclang -add-plugin -Xclang QTPlugin -c ./ViewController.m
就是这个类似用终端校验的指令、

**Comment by LLLaiYoung** [comment]
clang路径、Xcode路径和插件名对了吗？
