### ISSUE TITLE
xcode11配置完CC/CXX之后run报错Abort trap: 6

### ISSUE THREAD

**Issue by binzi56** [CYBoys/Blogs#7]
写的挺详细的, xcode11配置完CC/CXX之后run显示
Unable to execute command: Abort trap: 6
Clang frontend command failed due to signal (use -v to see invocation)
这应该怎么处理呢

**Comment by LLLaiYoung** [comment]
确保每一步都按照文章来了么？如果还有问题，加我vx：LaiYoung_ 加的时候请备注来意。

**Comment by binzi56** [comment]
> 确保每一步都按照文章来了么？如果还有问题，加我vx：LaiYoung_ 加的时候请备注来意。

已加

前面所有的步骤都跟图里的一样, 之前`Enable Index-Wihle-Building Functionality`为`default`的时候报错也一样, 但是设置完CC/CXX后run报错, 我试了用终端也是一样的错误;
